document.writeln("<script>");
document.writeln("var highlight = document.createElement(\'highlight\');");
document.writeln("</script>");
document.writeln("<style>");
document.writeln("highlight{");
document.writeln("    color:black;");
document.writeln("    background-color:black;");
document.writeln("    text-align:center;");
document.writeln("}");
document.writeln("highlight:hover{");
document.writeln("    color:white;");
document.writeln("    background-color:black;");
document.writeln("    text-align:center;");
document.writeln("}");
document.writeln("</style>");